### ISSUE TITLE
Add support for Pinyin?

### ISSUE THREAD

**Issue by RuixiZhang42** [mass-driver/md-io#10]
I&nbsp;started to play around with the Ultra style, and it looks pretty rad. I&nbsp;wondered if you could add some glyphs so that MD&nbsp;IO would support [Hanyu Pinyin](https://en.wikipedia.org/wiki/Pinyin).

![pinyin-1](https://user-images.githubusercontent.com/39968857/144172038-21bce440-c8eb-4978-b0c2-22b8a25da954.png)

Two considerations:
1. **Character/glyph set.** The complete table is on [Wikipedia](https://en.wikipedia.org/wiki/Pinyin#Unicode_code_points). The common letters are `a`, `e`, `i`, `o`, `u`, `ü`; either without tone mark or with one of four tone marks (macron, acute, caron, grave); in both uppercase and lowercase. So, that’s a total of 6×5×2=60 glyphs, but many of them are already there. Rare letters are, well, rarely used (they are used for local dialects).
2. **Acute accent as second tone (rising tone) mark.** The western acute is written from top-right to bottom-left, so its shape is usually wider at the top and narrower at the bottom. However, the second tone mark is written from bottom-left to top-right, so its shape should be wider at the *bottom* and narrower at the *top*. This alternative acute shape could perhaps be implemented as a stylistic set.

**Comment by rutherfordcraze** [comment]
Thanks for the proposal, and sorry it’s taken this long to address!

Version 0.5 is out next week, and it includes support for the ‘common letter’ pinyin codepoints (`ǍǏǑǓǗǙǛǕǎǐǒǔǘǚǜǖ` were the only ones not already present).

Regarding your second point, I’m not sure I agree without having seen more examples. MD IO’s underlying contrast model is derived from a pointed-nib pen, the strokes of which vary in weight largely according to pressure. I can understand the logic of a calligraphy brush producing a stroke which is widest at the initial point of contact, but this wouldn’t be the case for a pointed nib — the mark could be wider at either end, and the convention seems to be that it’s always narrowest at the bottom.

I’m totally open to being wrong about this though! My understanding of pinyin is admittedly limited, so it’s entirely possible I’ve been looking at the wrong references so far.
