### ISSUE TITLE
Further distinction between lowercase /l and numeral one

### ISSUE THREAD

**Issue by rutherfordcraze** [mass-driver/md-io#2]
Lowercase `l` and numeral `1` may need to be more clearly distinguished from one another.

Some of the early versions of IO had an `l` without the lower left serif, which solves the problem but creates other issues relating to texture and spacing. Eventually I reverted to the current design, on the basis that most IDEs will already distinguish numbers by colour. That was enough for my own use, but for other use cases it may be worth finding a better solution.

Worth considering:
- Increase the angle of `1` diagonal stroke
- Remove `1` lower serifs
- Try other half-serif `l` constructions (sharp corner, wider)

**Comment by Evotron** [comment]
What are you thoughts on this `l`? 
![hockey stick l MD IO-01](https://user-images.githubusercontent.com/46901105/104353092-802afc00-54d5-11eb-98d8-866ba02a572c.png)

P.S. Thanks for the great typeface.

**Comment by rutherfordcraze** [comment]
Thanks! It’s a good design in concept, and I think it works well enough in the regular weight, but its issues become more pronounced as the weight increases.

<img width="1086" alt="MD IO early version lowercase l" src="https://user-images.githubusercontent.com/17358105/104360234-0ca6e000-5511-11eb-81f8-07c0bc8d65f0.png">

This was a version from early December — I think the spacing in the bold (still very WIP) becomes too uneven for me to be comfortable with. With any monospace there will be flaws, but the released design having a consistent line along the bottom of the character keeps the word from falling apart at least.

**Comment by Evotron** [comment]
😮 you’re so right

**Comment by rutherfordcraze** [comment]
Some explorations relating to the `1`:

<img width="1355" alt="Variations of numeral one" src="https://user-images.githubusercontent.com/17358105/104581353-be075c00-565e-11eb-94ae-9feccb87d6bd.png">


- a: V0.1 design.
- b: Steeper diagonal angle. In the current design, every terminal ends at either 0° or 90° — this is starting to cause tension here, with the lower part of the diagonal stroke becoming quite sharp.
- c: Steeper diagonal angle, off-angle cut. I tried to end the diagonal perpendicular to its stroke direction, which looks neater but this terminal is out of character with the rest of the typeface.
- d: No serifs. This creates some spacing issues with other numbers. I lengthened the diagonal to try and deal with that, but it’s not a perfect solution.
- e: No serifs, steeper diagonal angle, off-angle cut. As before, this alleviates the spacing issue a bit by splitting up the space on the left. Although again, as before, the terminal style is out of character.

It wouldn't be impossible to just adopt the off-angle terminal here for the sake of clarity, but only as a last resort. My own preference is _b,_ though it’s not a perfect solution — I’ll keep thinking about options.

**Comment by rutherfordcraze** [comment]
I’m settling for now on this design (below), which is based on _b_ from the image above but with some changes to the weight and the light trap in the apex. This’ll be included in the 0.2 release, but of course might change later.

<img width="1008" alt="New numeral one design" src="https://user-images.githubusercontent.com/17358105/108346913-332afb80-71e0-11eb-89c6-97fef8d5bcaa.png">
