### ISSUE TITLE
λ character

### ISSUE THREAD

**Issue by stenson** [mass-driver/md-io#5]
Been using MDIO in VSCode the last few days and really enjoying it!

An esoteric and very unimportant request, but I use the lamda/lambda character λ (`0x3bb`) quite a bit in my code, and it would be awesome to have that in MDIO.

**Comment by rutherfordcraze** [comment]
Hey Rob!
Consider this coming in 0.2 — I’ve also seen it used in CLI prompts, which is all the more reason to add it now :)

Might take another look at the shape later, but for now:
<img width="902" alt="Lambda glyph example" src="https://user-images.githubusercontent.com/17358105/105072543-379bb180-5a86-11eb-8183-7df41957ef30.png">

**Comment by stenson** [comment]
awesome! — thank you!
