### ISSUE TITLE
Do you plan to make it a variable font ?

### ISSUE THREAD

**Issue by alienlebarge** [mass-driver/md-io#6]
Hey,

Do you plan to make it a variable font ?

My main use of fonts are for web. Variable fonts are so usefull  (and fun) to use on this medium.

✌️

**Comment by rutherfordcraze** [comment]
Hey! In theory, yes — I’m keeping the outlines compatible between weights with this in mind.

In practice, building a variable font is a bit more involved than just hitting 'export as variable' (or an equivalent), so it might still be a while before I can include variable fonts in the Future Fonts release. Once I’m more confident about things like the weight/axis mappings and style names, then I think a variable font would be a good addition.
